eureka:
  instance:
   hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:

    
        - id: booking_details
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v3/**
            
            
        
                